### ISSUE TITLE
OH GOD I WAS LOOKING RIGHT AT IT

### ISSUE THREAD

**Issue by dbrady** [dbrady/test_driven_lighting#5]
i agm now blidn in both eye.s does you company help with pas for my eyes doctor?? please adivse soonest thanks

**Comment by ashtony42** [comment]
have you tried turning the bulb off and back on?

**Comment by dbrady** [comment]
can sobmody tell me if there haev been any replies to this thx

**Comment by ashtony42** [comment]
No, we've outsourced our higher tier support to a gnome village in the Feywild. You'll need to contact our liaison at the portal between realms who can translate your common tongue to sylvan. So that our experts can forward your inquiry. We humbly apologize, as our technicians have truesight for the purposes of testing all frequencies of light to ensure that all of our users can utilize our lights to the fullest.

**Comment by dbrady** [comment]
colsed issue pendnig eye tarnspalnt srugery
